[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "drawbot_control"
requires-python = ">=3.9"

[tool.maturin]
python-source = "python"
module-name = "drawbot_control.gcode_wrangler"